### ISSUE TITLE
part 3/ Set Base Token URI fails 

### ISSUE THREAD

**Issue by AndreaDiPiPietro** [ProjectOpenSea/nft-tutorial#6]
Double checking for typos in my code, everything is as it should be, and the "token-uri" task was returning an error.
I checked and no uri was in the response, so I checked on Etherscan and every "set-base-token-uri" task I called failed.
I wasn't given any error in console and Etherscan only says it failed.
Someone might have an idea of why this is happening?

**Comment by cronoklee** [comment]
It's not really needed at all. I just set my _baseURI function to return the hard-coded path to my meta data and it worked fine:

        function _baseURI() internal view virtual override returns (string memory) {
		return "ipfs://...etc";
	}
I didnt need to call `set-base-token-uri` then either which saved some gas fees.

**Comment by AndreaDiPiPietro** [comment]
I'm new on this stuff and I overlooked the addresses, it worked like a charm!
